services:
    app:
        build:
            context: ..
            dockerfile: docker/app/Dockerfile
        volumes:
            - ./app.profile:/root/.profile:ro
            - ../.env.example:/var/www/html/.env.example:ro
            - ../.devcontainer:/var/www/html/.devcontainer
            - ../.git:/var/www/html/.git
            - ../.github:/var/www/html/.github
            - ../docker:/var/www/html/docker
            - ../documents:/var/www/html/documents
        network_mode: "service:web"

    web:
        build:
            context: ..
            dockerfile: docker/nginx/Dockerfile
        ports:
            - 8080:80

volumes:
    app-vendor:

